using System;
using System.Linq;
using AlphaVantageApi;
using Common;
using StockWatchData.Models;

namespace AlphaVantageScraper
{
  class Program
  {
    static void Main(string[] args)
    {
      var dataContextFactory = new SqlServerStockWatchDataContextFactory();
      AlphaVantageScraper scraper =
        new AlphaVantageScraper(new AlphaVantage(""), dataContextFactory);

      var sp500 = new[]
      {
        "A", "AAL", "AAP", "AAPL", "ABBV", "ABC", "ABT", "ACN", "ADBE", "ADI", "ADM", "ADP", "ADS",
        "ADSK", "AEE", "AEP", "AES", "AET", "AFL", "AGN", "AIG", "AIV", "AIZ", "AJG", "AKAM", "ALB",
        "ALGN", "ALK", "ALL", "ALLE", "ALXN", "AMAT", "AMD", "AME", "AMG", "AMGN", "AMP", "AMT",
        "AMZN", "ANDV", "ANSS", "ANTM", "AON", "AOS", "APA", "APC", "APD", "APH", "APTV", "ARE",
        "ARNC", "ATVI", "AVB", "AVGO", "AVY", "AWK", "AXP", "AYI", "AZO", "BA", "BAC", "BAX", "BBT",
        "BBY", "BDX", "BEN", "BF.B", "BHF", "BHGE", "BIIB", "BK", "BKNG", "BLK", "BLL", "BMY",
        "BRK.B", "BSX", "BWA", "BXP", "C", "CA", "CAG", "CAH", "CAT", "CB", "CBOE", "CBRE", "CBS",
        "CCI", "CCL", "CDNS", "CELG", "CERN", "CF", "CFG", "CHD", "CHRW", "CHTR", "CI", "CINF",
        "CL", "CLX", "CMA", "CMCSA", "CME", "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COG", "COL",
        "COO", "COP", "COST", "COTY", "CPB", "CRM", "CSCO", "CSX", "CTAS", "CTL", "CTSH", "CTXS",
        "CVS", "CVX", "CXO", "D", "DAL", "DE", "DFS", "DG", "DGX", "DHI", "DHR", "DIS", "DISCA",
        "DISCK", "DISH", "DLR", "DLTR", "DOV", "DPS", "DRE", "DRI", "DTE", "DUK", "DVA", "DVN",
        "DWDP", "DXC", "EA", "EBAY", "ECL", "ED", "EFX", "EIX", "EL", "EMN", "EMR", "EOG", "EQIX",
        "EQR", "EQT", "ES", "ESRX", "ESS", "ETFC", "ETN", "ETR", "EVHC", "EW", "EXC", "EXPD",
        "EXPE", "EXR", "F", "FAST", "FB", "FBHS", "FCX", "FDX", "FE", "FFIV", "FIS", "FISV", "FITB",
        "FL", "FLIR", "FLR", "FLS", "FMC", "FOX", "FOXA", "FRT", "FTI", "FTV", "GD", "GE", "GGP",
        "GILD", "GIS", "GLW", "GM", "GOOG", "GOOGL", "GPC", "GPN", "GPS", "GRMN", "GS", "GT", "GWW",
        "HAL", "HAS", "HBAN", "HBI", "HCA", "HCP", "HD", "HES", "HIG", "HII", "HLT", "HOG", "HOLX",
        "HON", "HP", "HPE", "HPQ", "HRB", "HRL", "HRS", "HSIC", "HST", "HSY", "HUM", "IBM", "ICE",
        "IDXX", "IFF", "ILMN", "INCY", "INFO", "INTC", "INTU", "IP", "IPG", "IPGP", "IQV", "IR",
        "IRM", "ISRG", "IT", "ITW", "IVZ", "JBHT", "JCI", "JEC", "JNJ", "JNPR", "JPM", "JWN", "K",
        "KEY", "KHC", "KIM", "KLAC", "KMB", "KMI", "KMX", "KO", "KORS", "KR", "KSS", "KSU", "L",
        "LB", "LEG", "LEN", "LH", "LKQ", "LLL", "LLY", "LMT", "LNC", "LNT", "LOW", "LRCX", "LUK",
        "LUV", "LYB", "M", "MA", "MAA", "MAC", "MAR", "MAS", "MAT", "MCD", "MCHP", "MCK", "MCO",
        "MDLZ", "MDT", "MET", "MGM", "MHK", "MKC", "MLM", "MMC", "MMM", "MNST", "MO", "MON", "MOS",
        "MPC", "MRK", "MRO", "MS", "MSCI", "MSFT", "MSI", "MTB", "MTD", "MU", "MYL", "NAVI", "NBL",
        "NCLH", "NDAQ", "NEE", "NEM", "NFLX", "NFX", "NI", "NKE", "NKTR", "NLSN", "NOC", "NOV",
        "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NWL", "NWS", "NWSA", "O", "OKE", "OMC",
        "ORCL", "ORLY", "OXY", "PAYX", "PBCT", "PCAR", "PCG", "PEG", "PEP", "PFE", "PFG", "PG",
        "PGR", "PH", "PHM", "PKG", "PKI", "PLD", "PM", "PNC", "PNR", "PNW", "PPG", "PPL", "PRGO",
        "PRU", "PSA", "PSX", "PVH", "PWR", "PX", "PXD", "PYPL", "QCOM", "QRVO", "RCL", "RE", "REG",
        "REGN", "RF", "RHI", "RHT", "RJF", "RL", "RMD", "ROK", "ROP", "ROST", "RRC", "RSG", "RTN",
        "SBAC", "SBUX", "SCG", "SCHW", "SEE", "SHW", "SIVB", "SJM", "SLB", "SLG", "SNA", "SNPS",
        "SO", "SPG", "SPGI", "SRCL", "SRE", "STI", "STT", "STX", "STZ", "SWK", "SWKS", "SYF", "SYK",
        "SYMC", "SYY", "T", "TAP", "TDG", "TEL", "TGT", "TIF", "TJX", "TMK", "TMO", "TPR", "TRIP",
        "TROW", "TRV", "TSCO", "TSN", "TSS", "TTWO", "TWX", "TXN", "TXT", "UA", "UAA", "UAL", "UDR",
        "UHS", "ULTA", "UNH", "UNM", "UNP", "UPS", "URI", "USB", "UTX", "V", "VAR", "VFC", "VIAB",
        "VLO", "VMC", "VNO", "VRSK", "VRSN", "VRTX", "VTR", "VZ", "WAT", "WBA", "WDC", "WEC",
        "WELL", "WFC", "WHR", "WLTW", "WM", "WMB", "WMT", "WRK", "WU", "WY", "WYN", "WYNN", "XEC",
        "XEL", "XL", "XLNX", "XOM", "XRAY", "XRX", "XYL", "YUM", "ZBH", "ZION", "ZTS"
      }.Select(s => s.ToLower()).ToArray();

      var nasdaq = new[]
      {
        "GASS", "GBCI", "GBDC", "GBLI", "GBLIL", "GBLIZ", "GBNK", "GBT", "GCBC",
        "GCVRZ", "GDEN", "GDS", "GEC", "GECC", "GECCL", "GECCM", "GEMP", "GENC", "GENE", "GENY",
        "GEOS", "GERN", "GEVO", "GFED", "GFN", "GFNCP", "GFNSL", "GGAL", "GHDX", "GIFI", "GIGM",
        "GIII", "GILD", "GILT", "GLAD", "GLADN", "GLBS", "GLBZ", "GLDD", "GLDI", "GLIBA", "GLIBP",
        "GLMD", "GLNG", "GLPG", "GLPI", "GLRE", "GLUU", "GLYC", "GMLP", "GMLPP", "GNBC", "GNCA",
        "GNMA", "GNMK", "GNMX", "GNPX", "GNRX", "GNTX", "GNTY", "GNUS", "GOGL", "GOGO", "GOLD",
        "GOOD", "GOODM", "GOODO", "GOODP", "GOOG", "GOOGL", "GOV", "GOVNI", "GPAQ", "GPAQU",
        "GPAQW", "GPIC", "GPOR", "GPP", "GPRE", "GPRO", "GRBIC", "GRBK", "GRFS", "GRID", "GRIF",
        "GRMN", "GROW", "GRPN", "GRVY", "GSBC", "GSHD", "GSHT", "GSHTU", "GSHTW", "GSIT", "GSM",
        "GSUM", "GSVC", "GT", "GTHX", "GTIM", "GTLS", "GTXI", "GTYH", "GTYHU", "GTYHW", "GULF",
        "GURE", "GVP", "GWGH", "GWPH", "GWRS", "GYRO", "HA", "HABT", "HAFC", "HAIN", "HAIR", "HALL",
        "HALO", "HAS", "HAWK", "HAYN", "HBAN", "HBANN", "HBANO", "HBCP", "HBHC", "HBHCL", "HBIO",
        "HBK", "HBMD", "HBNC", "HBP", "HCAP", "HCAPZ", "HCCI", "HCKT", "HCM", "HCOM", "HCSG",
        "HDNG", "HDP", "HDS", "HDSN", "HEAR", "HEBT", "HEES", "HELE", "HEWG", "HFBC", "HFBL",
        "HFGIC", "HFWA", "HGSH", "HIBB", "HIFS", "HIHO", "HIIQ", "HIMX", "HLG", "HLIT", "HLNE",
        "HMHC", "HMNF", "HMNY", "HMST", "HMSY", "HMTA", "HMTV", "HNDL", "HNNA", "HNRG", "HOFT",
        "HOLI", "HOLX", "HOMB", "HONE", "HOPE", "HOVNP", "HPJ", "HPT", "HQCL", "HQY", "HRTX",
        "HRZN", "HSDT", "HSGX", "HSIC", "HSII", "HSKA", "HSON", "HSTM", "HTBI", "HTBK", "HTBX",
        "HTGM", "HTHT", "HTLD", "HTLF", "HUBG", "HUNT", "HUNTU", "HUNTW", "HURC", "HURN", "HVBC",
        "HWBK", "HWCC", "HWKN", "HX", "HYAC", "HYACU", "HYACW", "HYGS", "HYLS", "HYND", "HYXE",
        "HYZD", "HZNP", "IAC", "IAM", "IAMXR", "IAMXW", "IART", "IBB", "IBCP", "IBKC", "IBKCO",
        "IBKCP", "IBKR", "IBOC", "IBTX", "IBUY", "ICAD", "ICBK", "ICCC", "ICCH", "ICFI", "ICHR",
        "ICLK", "ICLN", "ICLR", "ICON", "ICPT", "ICUI", "IDCC", "IDLB", "IDRA", "IDSA", "IDSY",
        "IDTI", "IDXG", "IDXX", "IEA", "IEAWW", "IEF", "IEI", "IEP", "IESC", "IEUS", "IFEU", "IFGL",
        "IFMK", "IFON", "IFRX", "IFV", "IGF", "IGLD", "IGOV", "III", "IIIN", "IIJI", "IIN", "IIVI",
        "IJT", "IKNX", "ILG", "ILMN", "ILPT", "IMDZ", "IMGN", "IMI", "IMKTA", "IMMP", "IMMR",
        "IMMU", "IMMY", "IMNP", "IMOS", "IMPV", "IMRN", "IMRNW", "IMTE", "INAP", "INBK", "INBKL",
        "INCY", "INDB", "INDU", "INDUU", "INDUW", "INDY", "INFI", "INFN", "INFO", "INFR", "INGN",
        "INNT", "INO", "INOD", "INOV", "INPX", "INSE", "INSG", "INSM", "INSY", "INTC", "INTG",
        "INTL", "INTU", "INTX", "INVA", "INVE", "INWK", "IONS", "IOSP", "IOTS", "IOVA", "IPAR",
        "IPAS", "IPCC", "IPCI", "IPDN", "IPGP", "IPHS", "IPIC", "IPKW", "IPWR", "IQ", "IRBT",
        "IRCP", "IRDM", "IRDMB", "IRIX", "IRMD", "IROQ", "IRTC", "IRWD", "ISBC", "ISCA", "ISHG",
        "ISIG", "ISNS", "ISRG", "ISRL", "ISSC", "ISTB", "ISTR", "ITCI", "ITEQ", "ITI", "ITIC",
        "ITRI", "ITRN", "ITUS", "IUSB", "IUSG", "IUSV", "IVAC", "IVENC", "IVFGC", "IVFVC", "IVTY",
        "IXUS", "IZEA", "JACK", "JAGX", "JAKK", "JASN", "JASNW", "JASO", "JAZZ", "JBHT", "JBLU",
        "JBSS", "JCOM", "JCS", "JCTCF", "JD", "JJSF", "JKHY", "JKI", "JMBA", "JMU", "JNCE", "JNP",
        "JOBS", "JOUT", "JRJC", "JRSH", "JRVR", "JSM", "JSMD", "JSML", "JSYN", "JSYNR", "JSYNU",
        "JSYNW", "JTPY", "JVA", "JXSB", "JYNT", "KAAC", "KAACU", "KAACW", "KALA", "KALU", "KALV",
        "KANG", "KBAL", "KBLM", "KBLMR", "KBLMU", "KBLMW", "KBSF", "KBWB", "KBWD", "KBWP", "KBWR",
        "KBWY", "KCAP", "KCAPL", "KE", "KELYA", "KELYB", "KEQU", "KERX", "KEYW", "KFFB", "KFRC",
        "KGJI", "KHC", "KIDS", "KIN", "KINS", "KIRK", "KLAC", "KLIC", "KLXI", "KMDA", "KMPH",
        "KNDI", "KNSL", "KONA", "KONE", "KOOL", "KOPN", "KOSS", "KPTI", "KRMA", "KRNT", "KRNY",
        "KRYS", "KTCC", "KTOS", "KTOV", "KTOVW", "KTWO", "KURA", "KVHI", "KWEB", "KZIA", "LABL",
        "LACQ", "LACQU", "LACQW", "LAKE", "LALT", "LAMR", "LANC", "LAND", "LANDP", "LARK", "LASR",
        "LAUR", "LAWS", "LAYN", "LAZY", "LBAI", "LBC", "LBIX", "LBRDA", "LBRDK", "LBTYA", "LBTYB",
        "LBTYK", "LCA", "LCAHU", "LCAHW", "LCNB", "LCUT", "LDRI", "LE", "LECO", "LEDS", "LEGR",
        "LENS", "LEVL", "LEXEA", "LEXEB", "LFIN", "LFUS", "LFVN", "LGCY", "LGCYO", "LGCYP", "LGIH",
        "LGND", "LHCG", "LIFE", "LILA", "LILAK", "LINC", "LIND", "LINDW", "LINK", "LION", "LITE",
        "LIVE", "LIVN", "LIVX", "LJPC", "LKFN", "LKOR", "LKQ", "LLEX", "LLIT", "LLNW", "LMAT",
        "LMB", "LMBS", "LMFA", "LMFAW", "LMNR", "LMNX", "LMRK", "LMRKN", "LMRKO", "LMRKP", "LNDC",
        "LNGR", "LNTH", "LOAN", "LOB", "LOCO", "LOGI", "LOGM", "LONE", "LOOP", "LOPE", "LORL",
        "LOXO", "LPCN", "LPLA", "LPNT", "LPSN", "LPTH", "LPTX", "LQDT", "LRAD", "LRCX", "LRGE",
        "LSBK", "LSCC", "LSTR", "LSXMA", "LSXMB", "LSXMK", "LTBR", "LTRPA", "LTRPB", "LTRX", "LTXB",
        "LULU", "LUNA", "LVHD", "LWAY", "LX", "LXRX", "LYL", "LYTS", "MACK", "MACQ", "MACQU",
        "MACQW", "MAGS", "MAMS", "MANH", "MANT", "MAR", "MARA", "MARK", "MARPS", "MASI", "MAT",
        "MATR", "MATW", "MAYS", "MB", "MBB", "MBCN", "MBFI", "MBFIO", "MBII", "MBIN", "MBIO",
        "MBOT", "MBRX", "MBSD", "MBTF", "MBUU", "MBVX", "MBWM", "MCBC", "MCEF", "MCEP", "MCFT",
        "MCHI", "MCHP", "MCHX", "MCRB", "MCRI", "MDB", "MDCA", "MDCO", "MDGL", "MDGS", "MDIV",
        "MDLZ", "MDRX", "MDSO", "MDWD", "MDXG", "MEDP", "MEET", "MEIP", "MELI", "MELR", "MEOH",
        "MERC", "MESO", "METC", "MFIN", "MFINL", "MFNC", "MFSF", "MGEE", "MGEN", "MGI", "MGIC",
        "MGLN", "MGNX", "MGPI", "MGRC", "MGYR", "MHLD", "MICT", "MIDD", "MIK", "MILN", "MIME",
        "MIND", "MINDP", "MINI", "MITK", "MITL", "MKGI", "MKSI", "MKTX", "MLAB", "MLCO", "MLHR",
        "MLNT", "MLNX", "MLVF", "MMAC", "MMDM", "MMDMR", "MMDMU", "MMDMW", "MMLP", "MMSI", "MMYT",
        "MNDO", "MNGA", "MNKD", "MNLO", "MNOV", "MNRO", "MNST", "MNTA", "MNTX", "MOBL", "MOFG",
        "MOGLC", "MOGO", "MOMO", "MOR", "MORN", "MOSY", "MOTS", "MOXC", "MPAA", "MPAC", "MPACU",
        "MPACW", "MPB", "MPCT", "MPVD", "MPWR", "MRAM", "MRBK", "MRCC", "MRCY", "MRLN", "MRNS",
        "MRSN", "MRTN", "MRTX", "MRUS", "MRVL", "MSBF", "MSBI", "MSCC", "MSEX", "MSFT", "MSG",
        "MSON", "MSTR", "MTBC", "MTBCP", "MTCH", "MTEC", "MTECU", "MTECW", "MTEM", "MTEX", "MTFB",
        "MTFBW", "MTGE", "MTGEP", "MTLS", "MTP", "MTRX", "MTSC", "MTSI", "MTSL", "MU", "MUDS",
        "MUDSU", "MUDSW", "MVBF", "MVIS", "MXIM", "MXWL", "MYGN", "MYL", "MYND", "MYNDW", "MYOK",
        "MYOS", "MYRG", "MYSZ", "MZOR", "NAII", "NAKD", "NANO", "NAOV", "NATH", "NATI", "NATR",
        "NAUH", "NAVG", "NAVI", "NBEV", "NBIX", "NBN", "NBRV", "NBTB", "NCBS", "NCLH", "NCMI",
        "NCNA", "NCOM", "NCSM", "NCTY", "NDAQ", "NDLS", "NDRA", "NDRAW", "NDSN", "NEBU", "NEBUU",
        "NEBUW", "NEO", "NEOG", "NEON", "NEOS", "NEPT", "NERV", "NESR", "NESRW", "NETE", "NEWA",
        "NEWT", "NEWTI", "NEWTZ", "NEXT", "NFBK", "NFEC", "NFLX", "NFTY", "NGHC", "NGHCN", "NGHCO",
        "NGHCP", "NGHCZ", "NH", "NHLD", "NHLDW", "NHTC", "NICE", "NICK", "NIHD", "NITE", "NK",
        "NKSH", "NKTR", "NLNK", "NLST", "NMIH", "NMRD", "NMRK", "NNBR", "NNDM", "NODK", "NOVN",
        "NOVT", "NRC", "NRIM", "NSEC", "NSIT", "NSSC", "NSTG", "NSYS", "NTAP", "NTCT", "NTEC",
        "NTES", "NTGR", "NTIC", "NTLA", "NTNX", "NTRA", "NTRI", "NTRP", "NTRS", "NTRSP", "NTWK",
        "NUAN", "NURO", "NUROW", "NUVA", "NVAX", "NVCN", "NVCR", "NVDA", "NVEC", "NVEE", "NVFY",
        "NVIV", "NVLN", "NVMI", "NVMM", "NVTR", "NVUS", "NWBI", "NWFL", "NWLI", "NWPX", "NWS",
        "NWSA", "NXEO", "NXEOU", "NXEOW", "NXPI", "NXST", "NXTD", "NXTDW", "NXTM", "NYMT", "NYMTN",
        "NYMTO", "NYMTP", "NYMX", "NYNY", "OASM", "OBAS", "OBCI", "OBLN", "OBNK", "OBSV", "OCC",
        "OCFC", "OCLR", "OCSI", "OCSL", "OCSLL", "OCUL", "ODFL", "ODP", "ODT", "OESX", "OFED",
        "OFIX", "OFLX", "OFS", "OFSSL", "OHAI", "OHGI", "OHRP", "OIIM", "OKDCC", "OKTA", "OLBK",
        "OLD", "OLED", "OLLI", "OMAB", "OMCL", "OMED", "OMER", "OMEX", "OMNT", "ON", "ONB", "ONCE",
        "ONCS", "ONEQ", "ONS", "ONSIW", "ONTX", "ONTXW", "ONVO", "OPB", "OPBK", "OPES", "OPESU",
        "OPESW", "OPGN", "OPGNW", "OPHC", "OPHT", "OPK", "OPNT", "OPOF", "OPTN", "OPTT", "ORBC",
        "ORBK", "ORG", "ORGS", "ORIG", "ORIT", "ORLY", "ORMP", "ORPN", "ORRF", "OSBC", "OSBCP",
        "OSIS", "OSN", "OSPR", "OSPRU", "OSPRW", "OSS", "OSTK", "OSUR", "OTEL", "OTEX", "OTIC",
        "OTIV", "OTTR", "OTTW", "OVAS", "OVBC", "OVID", "OVLY", "OXBR", "OXBRW", "OXFD", "OXLC",
        "OXLCM", "OXLCO", "OXSQ", "OXSQL", "OZRK", "PAAS", "PACB", "PACQU", "PACW", "PAGG", "PAHC",
        "PANL", "PATI", "PATK", "PAVM", "PAVMW", "PAVMZ", "PAYX", "PBBI", "PBCT", "PBCTP", "PBHC",
        "PBIB", "PBIP", "PBPB", "PBSK", "PBYI", "PCAR", "PCH", "PCMI", "PCOM", "PCRX", "PCSB",
        "PCTI", "PCTY", "PCYG", "PCYO", "PDBC", "PDCE", "PDCO", "PDEX", "PDFS", "PDLB", "PDLI",
        "PDP", "PDVW", "PEBK", "PEBO", "PEGA", "PEGI", "PEIX", "PENN", "PEP", "PERI", "PERY",
        "PESI", "PETQ", "PETS", "PETX", "PETZ", "PEY", "PEZ", "PFBC", "PFBI", "PFF", "PFG", "PFI",
        "PFIE", "PFIN", "PFIS", "PFLT", "PFM", "PFMT", "PFPT", "PFSW", "PGC", "PGJ", "PGLC", "PGNX",
        "PGTI", "PHII", "PHIIK", "PHO", "PI", "PICO", "PID", "PIE", "PIH", "PIHPP", "PINC", "PIO",
        "PIRS", "PIXY", "PIZ", "PKBK", "PKOH", "PKW", "PLAB", "PLAY", "PLBC", "PLCE", "PLLL",
        "PLPC", "PLSE", "PLUG", "PLUS", "PLW", "PLXP", "PLXS", "PLYA", "PMBC", "PMD", "PME", "PMOM",
        "PMPT", "PMTS", "PNBK", "PNFP", "PNK", "PNNT", "PNQI", "PNRG", "PNTR", "PODD", "POLA",
        "POOL", "POPE", "POWI", "POWL", "PPBI", "PPC", "PPH", "PPIH", "PPSI", "PRAA", "PRAH",
        "PRAN", "PRCP", "PRFT", "PRFZ", "PRGS", "PRGX", "PRIM", "PRKR", "PRMW", "PRN", "PROV",
        "PRPH", "PRPL", "PRPLW", "PRPO", "PRQR", "PRSC", "PRSS", "PRTA", "PRTK", "PRTO", "PRTS",
        "PS", "PSAU", "PSC", "PSCC", "PSCD", "PSCE", "PSCF", "PSCH", "PSCI", "PSCM", "PSCT", "PSCU",
        "PSDO", "PSEC", "PSET", "PSL", "PSMT", "PSTI", "PTC", "PTCT", "PTEN", "PTF", "PTGX", "PTH",
        "PTI", "PTIE", "PTLA", "PTNR", "PTSI", "PTX", "PUB", "PUI", "PULM", "PVAC", "PVAL", "PVBC",
        "PWOD", "PXI", "PXLW", "PXS", "PXUS", "PY", "PYDS", "PYPL", "PYZ", "PZZA", "QABA", "QADA",
        "QADB", "QAT", "QBAK", "QCLN", "QCOM", "QCRH", "QDEL", "QGEN", "QINC", "QIWI", "QLC",
        "QLYS", "QNST", "QQEW", "QQQ", "QQQC", "QQQX", "QQXT", "QRHC", "QRTEA", "QRTEB", "QRVO",
        "QSII", "QTEC", "QTNA", "QTNT", "QTRH", "QTRX", "QUIK", "QUMU", "QURE", "QYLD", "RADA",
        "RAIL", "RAND", "RARE", "RARX", "RAVE", "RAVN", "RBB", "RBBN", "RBCAA", "RBCN", "RBNC",
        "RCII", "RCKT", "RCKY", "RCM", "RCMT", "RCON", "RDCM", "RDFN", "RDHL", "RDI", "RDIB",
        "RDNT", "RDUS", "RDVT", "RDVY", "RDWR", "RECN", "REDU", "REFR", "REGI", "REGN", "REIS",
        "RELL", "RELV", "REPH", "RESN", "RETA", "RETO", "RFAP", "RFDI", "RFEM", "RFEU", "RFIL",
        "RGCO", "RGEN", "RGLD", "RGLS", "RGNX", "RGSE", "RIBT", "RIBTW", "RICK", "RIGL", "RILY",
        "RILYG", "RILYH", "RILYL", "RILYZ", "RING", "RIOT", "RKDA", "RLJE", "RMBL", "RMBS", "RMCF",
        "RMGN", "RMNI", "RMR", "RMTI", "RNDB", "RNDM", "RNDV", "RNEM", "RNET", "RNLC", "RNMC",
        "RNSC", "RNST", "RNWK", "ROAD", "ROBO", "ROBT", "ROCK", "ROIC", "ROKU", "ROLL", "ROSE",
        "ROSEU", "ROSEW", "ROSG", "ROST", "RP", "RPD", "RPIBC", "RPXC", "RRD", "RRGB", "RRR",
        "RSLS", "RSYS", "RTIX", "RTRX", "RTTR", "RUN", "RUSHA", "RUSHB", "RUTH", "RVEN", "RVLT",
        "RVNC", "RVSB", "RWLK", "RXII", "RXIIW", "RYAAY", "RYTM", "SABR", "SAEX", "SAFM", "SAFT",
        "SAGE", "SAIA", "SAL", "SALM", "SAMG", "SANM", "SANW", "SASR", "SATS", "SAUC", "SAVE",
        "SBAC", "SBBP", "SBBX", "SBCF", "SBFG", "SBFGP", "SBGI", "SBLK", "SBLKZ", "SBNY", "SBNYW",
        "SBOT", "SBPH", "SBRA", "SBRAP", "SBSI", "SBT", "SBUX", "SCAC", "SCACU", "SCACW", "SCHL",
        "SCHN", "SCKT", "SCON", "SCPH", "SCSC", "SCVL", "SCWX", "SCYX", "SCZ", "SDVY", "SEAC",
        "SECO", "SEDG", "SEED", "SEIC", "SEII", "SELB", "SELF", "SENEA", "SENEB", "SES", "SESN",
        "SFBC", "SFBS", "SFIX", "SFLY", "SFM", "SFNC", "SFST", "SGBX", "SGC", "SGEN", "SGH", "SGLB",
        "SGLBW", "SGMA", "SGMO", "SGMS", "SGOC", "SGRP", "SGRY", "SGYP", "SHBI", "SHEN", "SHIP",
        "SHIPW", "SHLD", "SHLDW", "SHLM", "SHLO", "SHOO", "SHOS", "SHPG", "SHSP", "SHV", "SHY",
        "SIEB", "SIEN", "SIFI", "SIFY", "SIGA", "SIGI", "SIGM", "SILC", "SIMO", "SINA", "SINO",
        "SIR", "SIRI", "SITO", "SIVB", "SKIS", "SKOR", "SKYS", "SKYW", "SKYY", "SLAB", "SLCT",
        "SLDB", "SLGL", "SLGN", "SLIM", "SLM", "SLMBP", "SLNO", "SLNOW", "SLP", "SLQD", "SLRC",
        "SLS", "SLVO", "SMBC", "SMBK", "SMCI", "SMCP", "SMED", "SMIT", "SMMF", "SMMT", "SMPL",
        "SMPLW", "SMRT", "SMSI", "SMTC", "SMTX", "SNBR", "SND", "SNDE", "SNDX", "SNES", "SNFCA",
        "SNGX", "SNGXW", "SNH", "SNHNI", "SNHNL", "SNHY", "SNLN", "SNMX", "SNNA", "SNOA", "SNOAW",
        "SNPS", "SNSR", "SNSS", "SOCL", "SODA", "SOFO", "SOHO", "SOHOB", "SOHOK", "SOHOO", "SOHU",
        "SONA", "SONC", "SORL", "SOXX", "SP", "SPAR", "SPCB", "SPEX", "SPHS", "SPI", "SPKE",
        "SPKEP", "SPLK", "SPNE", "SPNS", "SPOK", "SPPI", "SPRO", "SPRT", "SPSC", "SPTN", "SPWH",
        "SPWR", "SQBG", "SQLV", "SQQQ", "SQZZ", "SRAX", "SRCE", "SRCL", "SRCLP", "SRDX", "SRET",
        "SREV", "SRNE", "SRPT", "SRRA", "SRTS", "SRTSW", "SSB", "SSBI", "SSC", "SSFN", "SSKN",
        "SSLJ", "SSNC", "SSNT", "SSRM", "SSTI", "SSYS", "STAA", "STAF", "STBA", "STBZ", "STCN",
        "STDY", "STFC", "STKL", "STKS", "STLD", "STLR", "STLRU", "STLRW", "STML", "STMP", "STNL",
        "STNLU", "STNLW", "STPP", "STRA", "STRL", "STRM", "STRS", "STRT", "STX", "STXB", "SUMR",
        "SUNS", "SUNW", "SUPN", "SURF", "SUSB", "SUSC", "SVA", "SVBI", "SVRA", "SVVC", "SWIN",
        "SWIR", "SWKS", "SYBT", "SYBX", "SYKE", "SYMC", "SYNA", "SYNC", "SYNH", "SYNL", "SYNT",
        "SYPR", "SYRS", "TA", "TACO", "TACOW", "TACT", "TAIT", "TANH", "TANNI", "TANNL", "TANNZ",
        "TAPR", "TAST", "TATT", "TAX", "TAYD", "TBBK", "TBK", "TBNK", "TBPH", "TCBI", "TCBIL",
        "TCBIP", "TCBIW", "TCBK", "TCCO", "TCFC", "TCGP", "TCMD", "TCON", "TCPC", "TCRD", "TCX",
        "TDIV", "TEAM", "TECD", "TECH", "TEDU", "TELL", "TENX", "TERP", "TESS", "TFSL", "TGA",
        "TGEN", "TGLS", "TGTX", "THFF", "THRM", "THST", "TIBR", "TIBRU", "TIBRW", "TIG", "TILE",
        "TIPT", "TISA", "TITN", "TIVO", "TLF", "TLGT", "TLND", "TLT", "TMCXU", "TMSR", "TMUS",
        "TNAV", "TNDM", "TNTR", "TNXP", "TOCA", "TOPS", "TORC", "TOUR", "TOWN", "TPIC", "TPIV",
        "TQQQ", "TRCB", "TRCH", "TREE", "TRHC", "TRIB", "TRIL", "TRIP", "TRMB", "TRMD", "TRMK",
        "TRMT", "TRNC", "TRNS", "TROV", "TROW", "TRPX", "TRS", "TRST", "TRUP", "TRVG", "TRVN",
        "TSBK", "TSC", "TSCAP", "TSCO", "TSEM", "TSG", "TSLA", "TSRI", "TSRO", "TST", "TTD", "TTEC",
        "TTEK", "TTGT", "TTMI", "TTNP", "TTOO", "TTPH", "TTS", "TTWO", "TUES", "TUR", "TURN",
        "TUSA", "TUSK", "TVIX", "TVIZ", "TVTY", "TWIN", "TWMC", "TWNK", "TWNKW", "TWOU", "TXMD",
        "TXN", "TXRH", "TYHT", "TYME", "TYPE", "TZOO", "UAE", "UBCP", "UBFO", "UBIO", "UBNK",
        "UBNT", "UBOH", "UBSH", "UBSI", "UBX", "UCBA", "UCBI", "UCFC", "UCTT", "UDBI", "UEIC",
        "UEPS", "UFCS", "UFPI", "UFPT", "UG", "UGLD", "UHAL", "UIHC", "ULBI", "ULH", "ULTA", "ULTI",
        "UMBF", "UMPQ", "UMRX", "UNAM", "UNB", "UNFI", "UNIT", "UNTY", "UONE", "UONEK", "UPL",
        "UPLD", "URBN", "URGN", "USAK", "USAP", "USAT", "USATP", "USAU", "USCR", "USEG", "USLB",
        "USLM", "USLV", "USMC", "USOI", "UTHR", "UTMD", "UTSI", "UVSP", "VALU", "VALX", "VBFC",
        "VBIV", "VBLT", "VBND", "VBTX", "VC", "VCEL", "VCIT", "VCLT", "VCSH", "VCTR", "VCYT",
        "VDSI", "VEAC", "VEACU", "VEACW", "VECO", "VEON", "VERI", "VERU", "VETS", "VGIT", "VGLT",
        "VGSH", "VIA", "VIAB", "VIAV", "VICL", "VICR", "VIDI", "VIGI", "VIIX", "VIIZ", "VIRC",
        "VIRT", "VIVE", "VIVO", "VKTX", "VKTXW", "VLGEA", "VLRX", "VMBS", "VNDA", "VNET", "VNOM",
        "VNQI", "VOD", "VONE", "VONG", "VONV", "VOXX", "VRA", "VRAY", "VREX", "VRIG", "VRML",
        "VRNA", "VRNS", "VRNT", "VRSK", "VRSN", "VRTS", "VRTSP", "VRTU", "VRTX", "VSAR", "VSAT",
        "VSDA", "VSEC", "VSMV", "VSTM", "VTC", "VTGN", "VTHR", "VTIP", "VTIQU", "VTL", "VTNR",
        "VTSI", "VTVT", "VTWG", "VTWO", "VTWV", "VUSE", "VUZI", "VVPR", "VVUS", "VWOB", "VXRT",
        "VXUS", "VYGR", "VYMI", "WABC", "WAFD", "WAFDW", "WASH", "WATT", "WB", "WBA", "WCFB",
        "WDAY", "WDC", "WDFC", "WEB", "WEBK", "WEN", "WERN", "WETF", "WEYS", "WHF", "WHFBL", "WHLM",
        "WHLR", "WHLRD", "WHLRP", "WHLRW", "WIFI", "WILC", "WIN", "WINA", "WING", "WINS", "WIRE",
        "WIX", "WKHS", "WLDN", "WLFC", "WLTW", "WMGI", "WMGIZ", "WMIH", "WNEB", "WOOD", "WPRT",
        "WRLD", "WRLS", "WRLSR", "WRLSU", "WRLSW", "WSBC", "WSBF", "WSC", "WSCI", "WSCWW", "WSFS",
        "WSTG", "WSTL", "WTBA", "WTFC", "WTFCM", "WTFCW", "WVE", "WVFC", "WVVI", "WVVIP", "WWD",
        "WWR", "WYNN", "XBIO", "XBIT", "XCRA", "XEL", "XELA", "XELB", "XENE", "XENT", "XGTI",
        "XGTIW", "XLNX", "XLRN", "XNCR", "XNET", "XOG", "XOMA", "XONE", "XPER", "XPLR", "XRAY",
        "XSPA", "XSPL", "XT", "XTLB", "YDIV", "YECO", "YGYI", "YIN", "YLCO", "YLDE", "YNDX", "YOGA",
        "YORW", "YRCW", "YRIV", "YTEN", "YTRA", "YY", "Z", "ZAGG", "ZAIS", "ZBIO", "ZBRA", "ZEAL",
        "ZEUS", "ZFGN", "ZG", "ZGNX", "ZION", "ZIONW", "ZIONZ", "ZIOP", "ZIV", "ZIXI", "ZKIN",
        "ZLAB", "ZN", "ZNGA", "ZNWAA", "ZS", "ZSAN", "ZUMZ", "ZYNE", "TRUE"
      }.Select(s => s.ToLowerInvariant()).ToArray();

//      var db = dataContextFactory.DataContext;
//      db.AddSymbolsToGroup(sp500, "sp500").Wait();
//      db.SaveChanges();
      Console.WriteLine($"Adding {nasdaq.Length} stocks to database.");
      scraper.Scrape(nasdaq, "nasdaq").Wait();
    }
  }
}